# Generated by Django 3.1.2 on 2020-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(blank=True, default='TK', max_length=255, null=True),
        ),
    ]
