# Generated by Django 3.1.2 on 2020-11-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_auto_20201110_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
